// @generated by docs/bubble-to-prd/skills/gen_schema.py — enums espelhando option_sets do Bubble.
// Cada enum lista [db_value, display]. Códigos SEFAZ/Receita são transcrição literal.

export const TipoNF = [
  { value: 'nfe', label: 'NFe' },
  { value: 'nfce', label: 'NFCE' },
  { value: 'nfse', label: 'NFSe' },
] as const;
export type TipoNFValue = typeof TipoNF[number]['value'];

export const Frete_Nfe = [
  { value: 'emitente', label: 'Emitente' },
  { value: 'destinat_rio', label: 'Destinatário' },
  { value: 'sem_frete', label: 'Sem Frete' },
] as const;
export type Frete_NfeValue = typeof Frete_Nfe[number]['value'];

export const Role_user = [
  { value: 'empresa', label: 'Empresa' },
  { value: 'contador', label: 'Contador' },
] as const;
export type Role_userValue = typeof Role_user[number]['value'];

export const Status_nfs = [
  { value: 'cancelada', label: 'cancelada' },
  { value: 'pendente', label: 'pendente' },
  { value: 'ativa', label: 'ativa' },
] as const;
export type Status_nfsValue = typeof Status_nfs[number]['value'];

export const Type_itens = [
  { value: 'empresa', label: 'Empresa' },
  { value: 'pf', label: 'PF' },
] as const;
export type Type_itensValue = typeof Type_itens[number]['value'];

export const icms_origem = [
  { value: '0___nacional', label: '0 – Nacional' },
  { value: '1___estrangeira__importa__o_direta_', label: '1 – Estrangeira (importação direta)' },
  { value: '2___estrangeira__adquirida_no_mercado_interno_', label: '2 – Estrangeira (adquirida no mercado interno)' },
  { value: '3___nacional_com_mais_de_40__de_conte_do_estrangeiro', label: '3 – Nacional com mais de 40% de conteúdo estrangeiro' },
  { value: '4___nacional_produzida_atrav_s_de_processos_produtivos_b_sicos', label: '4 – Nacional produzida através de processos produtivos básicos' },
  { value: '5___nacional_com_menos_de_40__de_conte_do_estrangeiro', label: '5 – Nacional com menos de 40% de conteúdo estrangeiro' },
  { value: '6___estrangeira__importa__o_direta__sem_produto_nacional_similar', label: '6 – Estrangeira (importação direta) sem produto nacional similar' },
  { value: '7___estrangeira__adquirida_no_mercado_interno__sem_produto_nacional_similar', label: '7 – Estrangeira (adquirida no mercado interno) sem produto nacional similar' },
] as const;
export type icms_origemValue = typeof icms_origem[number]['value'];

export const Local_destino = [
  { value: '1___opera__o_interna', label: '1 – Operação interna' },
  { value: '2___opera__o_interestadual', label: '2 – Operação interestadual' },
  { value: '3___opera__o_com_exterior', label: '3 – Operação com exterior' },
] as const;
export type Local_destinoValue = typeof Local_destino[number]['value'];

export const Tipo_documento = [
  { value: '0___nota_fiscal_de_entrada', label: '0 – Nota Fiscal de Entrada' },
  { value: '1___nota_fiscal_de_sa_da', label: '1 – Nota Fiscal de Saída' },
] as const;
export type Tipo_documentoValue = typeof Tipo_documento[number]['value'];

export const forma_pagamento = [
  { value: '01__dinheiro', label: '01: Dinheiro' },
  { value: '02__cheque', label: '02: Cheque' },
  { value: '03__cart_o_de_cr_dito', label: '03: Cartão de Crédito' },
  { value: '04__cart_o_de_d_bito', label: '04: Cartão de Débito' },
  { value: '05__cr_dito_loja', label: '05: Crédito Loja' },
  { value: '10__vale_alimenta__o', label: '10: Vale Alimentação' },
  { value: '11__vale_refei__o', label: '11: Vale Refeição' },
  { value: '12__vale_presente', label: '12: Vale Presente' },
  { value: '13__vale', label: '13: Vale Combustível' },
  { value: '99__outros', label: '99: Outros' },
] as const;
export type forma_pagamentoValue = typeof forma_pagamento[number]['value'];

export const Inclui_no_total = [
  { value: '0___n_o', label: '0 – Não' },
  { value: '1___sim', label: '1 – Sim' },
] as const;
export type Inclui_no_totalValue = typeof Inclui_no_total[number]['value'];

export const Consumidor_final = [
  { value: '0___normal', label: '0 – Normal' },
  { value: '1___consumidor_final', label: '1 – Consumidor final' },
] as const;
export type Consumidor_finalValue = typeof Consumidor_final[number]['value'];

export const modalidade_frete = [
  { value: '0___por_conta_do_emitente', label: '0 – Por conta do emitente' },
  { value: '1___por_conta_do_destinat_rio', label: '1 – Por conta do destinatário' },
  { value: '2___por_conta_de_terceiros', label: '2 – Por conta de terceiros' },
  { value: '9___sem_frete', label: '9 – Sem frete' },
] as const;
export type modalidade_freteValue = typeof modalidade_frete[number]['value'];

export const Unidade_comercial = [
  { value: 'un', label: 'UN' },
  { value: 'kg', label: 'KG' },
  { value: 'l', label: 'L' },
] as const;
export type Unidade_comercialValue = typeof Unidade_comercial[number]['value'];

export const Finalidade_emiss_o = [
  { value: '1___normal', label: '1 – Normal' },
  { value: '2___complementar', label: '2 – Complementar' },
  { value: '3___nota_de_ajuste', label: '3 – Nota de ajuste' },
  { value: '4___devolu__o', label: '4 – Devolução' },
] as const;
export type Finalidade_emiss_oValue = typeof Finalidade_emiss_o[number]['value'];

export const presenca_comprador = [
  { value: '0___n_o_se_aplica__por_exemplo__para_a_nota_fiscal_complementar_ou_de_ajuste_', label: '0 – Não se aplica (por exemplo, para a Nota Fiscal complementar ou de ajuste)' },
  { value: '1___opera__o_presencial', label: '1 – Operação presencial' },
  { value: '2___opera__o_n_o_presencial__pela_internet', label: '2 – Operação não presencial, pela Internet' },
  { value: '3___opera__o_n_o_presencial__teleatendimento', label: '3 – Operação não presencial, Teleatendimento' },
  { value: '4___nfc_e_em_opera__o_com_entrega_em_domic_lio', label: '4 – NFC-e em operação com entrega em domicílio' },
  { value: '9___opera__o_n_o_presencial__outros', label: '9 – Operação não presencial, outros' },
] as const;
export type presenca_compradorValue = typeof presenca_comprador[number]['value'];

export const Status_declaracoes = [
  { value: 'pronta_para_enviar', label: 'pronta para enviar' },
  { value: 'enviando', label: 'enviando' },
  { value: 'enviada', label: 'enviada' },
  { value: 'erro', label: 'erro' },
] as const;
export type Status_declaracoesValue = typeof Status_declaracoes[number]['value'];

export const Forma_pagamento_nfe = [
  { value: 'dinheiro', label: 'Dinheiro' },
  { value: 'cheque', label: 'Cheque' },
  { value: 'cart_o_de_cr_dito', label: 'Cartão de Crédito' },
  { value: 'cart_o_de_d_bito', label: 'Cartão de Débito' },
  { value: 'cr_dito_loja', label: 'Crédito Loja' },
  { value: 'outros', label: 'Outros' },
] as const;
export type Forma_pagamento_nfeValue = typeof Forma_pagamento_nfe[number]['value'];

export const Natureza_operacao_nfe = [
  { value: 'venda_de_produto', label: 'Venda de produto' },
  { value: 'venda_de_produto_para_consumidor_final', label: 'Venda de produto para consumidor final' },
  { value: 'devolu__o_de_compra', label: 'Devolução de compra' },
  { value: 'devolu__o_de_venda', label: 'Devolução de venda' },
  { value: 'transfer_ncia_de_mercadoria', label: 'Transferência de mercadoria' },
  { value: 'remessa_para_conserto', label: 'Remessa para conserto' },
  { value: 'retorno_de_conserto', label: 'Retorno de conserto' },
  { value: 'remessa_para_demonstra__o', label: 'Remessa para demonstração' },
  { value: 'retorno_de_demonstra__o', label: 'Retorno de demonstração' },
  { value: 'remessa_por_conta_e_ordem', label: 'Remessa por conta e ordem' },
  { value: 'brinde_ou_bonifica__o', label: 'Brinde ou bonificação' },
  { value: 'doa__o', label: 'Doação' },
] as const;
export type Natureza_operacao_nfeValue = typeof Natureza_operacao_nfe[number]['value'];

export const status_guias_impostos = [
  { value: 'gerando', label: 'gerando' },
  { value: 'gerada', label: 'gerada' },
  { value: 'paga', label: 'paga' },
  { value: 'vencida', label: 'vencida' },
  { value: 'erro', label: 'erro' },
] as const;
export type status_guias_impostosValue = typeof status_guias_impostos[number]['value'];

export const natureza_operacao_nfse = [
  { value: '1__tributa__o_no_munic_pio', label: '1: Tributação no município' },
  { value: '2__tributa__o_fora_do_munic_pio', label: '2: Tributação fora do município' },
  { value: '3__isen__o', label: '3: Isenção' },
  { value: '4__imune', label: '4: Imune' },
  { value: '5__exigibilidade_suspensa_por_decis_o_judicial', label: '5: Exigibilidade suspensa por decisão judicial' },
  { value: '6__exigibilidade_suspensa_por_procedimento_administrativo', label: '6: Exigibilidade suspensa por procedimento administrativo' },
] as const;
export type natureza_operacao_nfseValue = typeof natureza_operacao_nfse[number]['value'];

export const icms_situacao_tributaria = [
  { value: '00___tributada_integralmente', label: '00 – Tributada integralmente' },
  { value: '10___tributada_e_com_cobran_a_do_icms_por_substitui__o_tribut_ria', label: '10 – Tributada e com cobrança do ICMS por substituição tributária' },
  { value: '20___tributada_com_redu__o_de_base_de_c_lculo', label: '20 – Tributada com redução de base de cálculo' },
  { value: '30___isenta_ou_n_o_tributada_e_com_cobran_a_do_icms_por_substitui__o_tribut_ria', label: '30 – Isenta ou não tributada e com cobrança do ICMS por substituição tributária' },
  { value: '40___isenta', label: '40 – Isenta' },
  { value: '41___n_o_tributada', label: '41 – Não tributada' },
  { value: '50___suspens_o', label: '50 – Suspensão' },
  { value: '51___diferimento__a_exig_ncia_do_preenchimento_das_informa__es_do_icms_diferido_fica_a_crit_rio_de_cada_uf_', label: '51 – Diferimento (a exigência do preenchimento das informações do ICMS diferido fica a critério de cada UF)' },
  { value: '60___cobrado_anteriormente_por_substitui__o_tribut_ria', label: '60 – Cobrado anteriormente por substituição tributária' },
  { value: '70___tributada_com_redu__o_de_base_de_c_lculo_e_com_cobran_a_do_icms_por_substitui__o_tribut_ria__90___outras__regime_normal_', label: '70 – Tributada com redução de base de cálculo e com cobrança do ICMS por substituição tributária; 90 – Outras (regime Normal)' },
  { value: '101___ttributada_pelo_simples_nacional_com_permiss_o_de_cr_dito', label: '101 – Ttributada pelo Simples Nacional com permissão de crédito' },
  { value: '102___tributada_pelo_simples_nacional_sem_permiss_o_de_cr_dito', label: '102 – Tributada pelo Simples Nacional sem permissão de crédito' },
  { value: '103___isen__o_do_icms_no_simples_nacional_para_faixa_de_receita_bruta', label: '103 – Isenção do ICMS no Simples Nacional para faixa de receita bruta' },
  { value: '201___tributada_pelo_simples_nacional_com_permiss_o_de_cr_dito_e_com_cobran_a_do_icms_por_substitui__o_tribut_ria', label: '201 – Tributada pelo Simples Nacional com permissão de crédito e com cobrança do ICMS por substituição tributária' },
  { value: '202___tributada_pelo_simples_nacional_sem_permiss_o_de_cr_dito_e_com_cobran_a_do_icms_por_substitui__o_tribut_ria', label: '202 – Tributada pelo Simples Nacional sem permissão de crédito e com cobrança do ICMS por substituição tributária' },
  { value: '203___isen__o_do_icms_nos_simples_nacional_para_faixa_de_receita_bruta_e_com_cobran_a_do_icms_por_substitui__o_tribut_ria', label: '203 – Isenção do ICMS nos Simples Nacional para faixa de receita bruta e com cobrança do ICMS por substituição tributária' },
  { value: '300___imune', label: '300 – Imune' },
  { value: '400___n_o_tributada_pelo_simples_nacional', label: '400 – Não tributada pelo Simples Nacional' },
  { value: '500___icms_cobrado_anteriormente_por_substitui__o_tribut_ria__substitu_do__ou_por_antecipa__o', label: '500 – ICMS cobrado anteriormente por substituição tributária (substituído) ou por antecipação' },
  { value: '900___outras__regime_simples_nacional_', label: '900 – Outras (regime Simples Nacional)' },
  { value: 'pis_situacao_tributaria', label: 'pis_situacao_tributaria' },
  { value: '02___opera__o_tribut_vel', label: '02 – Operação tributável: base de cálculo = valor da operação (alíquota diferenciada)' },
  { value: '03___opera__o_tribut_vel__base_de_c_lculo___quantidade_vendida___al_quota_por_unidade_de_produto', label: '03 – Operação tributável: base de cálculo = quantidade vendida × alíquota por unidade de produto' },
  { value: '04___opera__o_tribut_vel__tributa__o_monof_sica__al_quota_zero_', label: '04 – Operação tributável: tributação monofásica (alíquota zero)' },
  { value: '05___opera__o_tribut_vel__substitui__o_tribut_ria', label: '05 – Operação tributável: substituição tributária' },
  { value: '06___opera__o_tribut_vel__al_quota_zero', label: '06 – Operação tributável: alíquota zero' },
  { value: '07___opera__o_isenta_da_contribui__o', label: '07 – Operação isenta da contribuição' },
  { value: '08___opera__o_sem_incid_ncia_da_contribui__o', label: '08 – Operação sem incidência da contribuição' },
  { value: '09___opera__o_com_suspens_o_da_contribui__o', label: '09 – Operação com suspensão da contribuição' },
  { value: '49___outras_opera__es_de_sa_da', label: '49 – Outras operações de saída' },
  { value: '50___opera__o_com_direito_a_cr_dito__vinculada_exclusivamente_a_receita_tributada_no_mercado_interno', label: '50 – Operação com direito a crédito: vinculada exclusivamente a receita tributada no mercado interno' },
  { value: '51___opera__o_com_direito_a_cr_dito__vinculada_exclusivamente_a_receita_n_o_tributada_no_mercado_interno', label: '51 – Operação com direito a crédito: vinculada exclusivamente a receita não tributada no mercado interno' },
  { value: '52___opera__o_com_direito_a_cr_dito__vinculada_exclusivamente_a_receita_de_exporta__o', label: '52 – Operação com direito a crédito: vinculada exclusivamente a receita de exportação' },
  { value: '53___opera__o_com_direito_a_cr_dito__vinculada_a_receitas_tributadas_e_n_o_tributadas_no_mercado_interno', label: '53 – Operação com direito a crédito: vinculada a receitas tributadas e não-tributadas no mercado interno' },
  { value: '54___opera__o_com_direito_a_cr_dito__vinculada_a_receitas_tributadas_no_mercado_interno_e_de_exporta__o', label: '54 – Operação com direito a crédito: vinculada a receitas tributadas no mercado interno e de exportação' },
  { value: '55___opera__o_com_direito_a_cr_dito__vinculada_a_receitas_n_o_tributadas_no_mercado_interno_e_de_exporta__o', label: '55 – Operação com direito a crédito: vinculada a receitas não-tributadas no mercado interno e de exportação' },
  { value: '56___opera__o_com_direito_a_cr_dito__vinculada_a_receitas_tributadas_e_n_o_tributadas_no_mercado_interno_e_de_exporta__o', label: '56 – Operação com direito a crédito: vinculada a receitas tributadas e não-tributadas no mercado interno e de exportação' },
  { value: '60___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_exclusivamente_a_receita_tributada_no_mercado_interno', label: '60 – Crédito presumido: operação de aquisição vinculada exclusivamente a receita tributada no mercado interno' },
  { value: '61___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_exclusivamente_a_receita_n_o_tributada_no_mercado_interno', label: '61 – Crédito presumido: operação de aquisição vinculada exclusivamente a receita não-tributada no mercado interno' },
  { value: '62___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_exclusivamente_a_receita_de_exporta__o', label: '62 – Crédito presumido: operação de aquisição vinculada exclusivamente a receita de exportação' },
  { value: '63___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_a_receitas_tributadas_e_n_o_tributadas_no_mercado_interno', label: '63 – Crédito presumido: operação de aquisição vinculada a receitas tributadas e não-tributadas no mercado interno' },
  { value: '64___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_a_receitas_tributadas_no_mercado_interno_e_de_exporta__o', label: '64 – Crédito presumido: operação de aquisição vinculada a receitas tributadas no mercado interno e de exportação' },
  { value: '65___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_a_receitas_n_o_tributadas_no_mercado_interno_e_de_exporta__o', label: '65 – Crédito presumido: operação de aquisição vinculada a receitas não-tributadas no mercado interno e de exportação' },
  { value: '66___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_a_receitas_tributadas_e_n_o_tributadas_no_mercado_interno_e_de_exporta__o', label: '66 – Crédito presumido: operação de aquisição vinculada a receitas tributadas e não-tributadas no mercado interno e de exportação' },
  { value: '67___cr_dito_presumido__outras_opera__es', label: '67 – Crédito presumido: outras operações' },
  { value: '70___opera__o_de_aquisi__o_sem_direito_a_cr_dito', label: '70 – Operação de aquisição sem direito a crédito' },
  { value: '71___opera__o_de_aquisi__o_com_isen__o', label: '71 – Operação de aquisição com isenção' },
  { value: '72___opera__o_de_aquisi__o_com_suspens_o', label: '72 – Operação de aquisição com suspensão' },
  { value: '73___opera__o_de_aquisi__o_a_al_quota_zero', label: '73 – Operação de aquisição a alíquota zero' },
  { value: '74___opera__o_de_aquisi__o_sem_incid_ncia_da_contribui__o', label: '74 – Operação de aquisição sem incidência da contribuição' },
  { value: '75___opera__o_de_aquisi__o_por_substitui__o_tribut_ria', label: '75 – Operação de aquisição por substituição tributária' },
  { value: '98___outras_opera__es_de_entrada', label: '98 – Outras operações de entrada' },
  { value: '99___outras_opera__es', label: '99 – Outras operações' },
] as const;
export type icms_situacao_tributariaValue = typeof icms_situacao_tributaria[number]['value'];

export const regime_tributario_empresa = [
  { value: 'simples_nacional', label: 'Simples Nacional' },
  { value: 'simples_nacional___excesso_de_sublimite_de_receita_bruta', label: 'Simples Nacional — Excesso de sublimite de receita bruta' },
  { value: 'regime_normal__lucro_real_ou_presumido_', label: 'Regime Normal (Lucro Real ou Presumido)' },
  { value: 'simples_nacional___mei', label: 'Simples Nacional — MEI' },
] as const;
export type regime_tributario_empresaValue = typeof regime_tributario_empresa[number]['value'];

export const cofins_situacao_tributaria = [
  { value: '01___opera__o_tribut_vel__base_de_c_lculo___valor_da_opera__o__al_quota_normal___cumulativo_n_o_cumulativo_', label: '01 – Operação tributável: base de cálculo = valor da operação (alíquota normal – cumulativo/não cumulativo)' },
  { value: '02___opera__o_tribut_vel__base_de_c_lculo___valor_da_opera__o__al_quota_diferenciada_', label: '02 – Operação tributável: base de cálculo = valor da operação (alíquota diferenciada)' },
  { value: '03___opera__o_tribut_vel__base_de_c_lculo___quantidade_vendida___al_quota_por_unidade_de_produto', label: '03 – Operação tributável: base de cálculo = quantidade vendida × alíquota por unidade de produto' },
  { value: '04___opera__o_tribut_vel__tributa__o_monof_sica__al_quota_zero_', label: '04 – Operação tributável: tributação monofásica (alíquota zero)' },
  { value: '05___opera__o_tribut_vel__substitui__o_tribut_ria', label: '05 – Operação tributável: substituição tributária' },
  { value: '06___opera__o_tribut_vel__al_quota_zero', label: '06 – Operação tributável: alíquota zero' },
  { value: '07___opera__o_isenta_da_contribui__o', label: '07 – Operação isenta da contribuição' },
  { value: '08___opera__o_sem_incid_ncia_da_contribui__o', label: '08 – Operação sem incidência da contribuição' },
  { value: '09___opera__o_com_suspens_o_da_contribui__o', label: '09 – Operação com suspensão da contribuição' },
  { value: '49___outras_opera__es_de_sa_da', label: '49 – Outras operações de saída' },
  { value: '50___opera__o_com_direito_a_cr_dito__vinculada_exclusivamente_a_receita_tributada_no_mercado_interno', label: '50 – Operação com direito a crédito: vinculada exclusivamente a receita tributada no mercado interno' },
  { value: '51___opera__o_com_direito_a_cr_dito__vinculada_exclusivamente_a_receita_n_o_tributada_no_mercado__interno', label: '51 – Operação com direito a crédito: vinculada exclusivamente a receita não tributada no mercado  interno' },
  { value: '52___opera__o_com_direito_a_cr_dito__vinculada_exclusivamente_a_receita_de_exporta__o', label: '52 – Operação com direito a crédito: vinculada exclusivamente a receita de exportação' },
  { value: '53___opera__o_com_direito_a_cr_dito__vinculada_a_receitas_tributadas_e_n_o_tributadas_no_mercado_interno', label: '53 – Operação com direito a crédito: vinculada a receitas tributadas e não-tributadas no mercado interno' },
  { value: '54___opera__o_com_direito_a_cr_dito__vinculada_a_receitas_tributadas_no_mercado_interno_e_de_exporta__o', label: '54 – Operação com direito a crédito: vinculada a receitas tributadas no mercado interno e de exportação' },
  { value: '55___opera__o_com_direito_a_cr_dito__vinculada_a_receitas_n_o_tributadas_no_mercado_interno_e_de_exporta__o', label: '55 – Operação com direito a crédito: vinculada a receitas não-tributadas no mercado interno e de exportação' },
  { value: '56___opera__o_com_direito_a_cr_dito__vinculada_a_receitas_tributadas_e_n_o_tributadas_no_mercado_interno_e_de_exporta__o', label: '56 – Operação com direito a crédito: vinculada a receitas tributadas e não-tributadas no mercado interno e de exportação' },
  { value: '60___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_exclusivamente_a_receita_tributada_no_mercado_interno', label: '60 – Crédito presumido: operação de aquisição vinculada exclusivamente a receita tributada no mercado interno' },
  { value: '61___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_exclusivamente_a_receita_n_o_tributada_no_mercado_interno', label: '61 – Crédito presumido: operação de aquisição vinculada exclusivamente a receita não-tributada no mercado interno' },
  { value: '62___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_exclusivamente_a_receita_de_exporta__o', label: '62 – Crédito presumido: operação de aquisição vinculada exclusivamente a receita de exportação' },
  { value: '63___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_a_receitas_tributadas_e_n_o_tributadas_no_mercado_interno', label: '63 – Crédito presumido: operação de aquisição vinculada a receitas tributadas e não-tributadas no mercado interno' },
  { value: '64___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_a_receitas_tributadas_no_mercado_interno_e_de_exporta__o', label: '64 – Crédito presumido: operação de aquisição vinculada a receitas tributadas no mercado interno e de exportação' },
  { value: '65___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_a_receitas_n_o_tributadas_no_mercado_interno_e_de_exporta__o', label: '65 – Crédito presumido: operação de aquisição vinculada a receitas não-tributadas no mercado interno e de exportação' },
  { value: '66___cr_dito_presumido__opera__o_de_aquisi__o_vinculada_a_receitas_tributadas_e_n_o_tributadas_no_mercado_interno_e_de_exporta__o', label: '66 – Crédito presumido: operação de aquisição vinculada a receitas tributadas e não-tributadas no mercado interno e de exportação' },
  { value: '67___cr_dito_presumido__outras_opera__es', label: '67 – Crédito presumido: outras operações' },
  { value: '70___opera__o_de_aquisi__o_sem_direito_a_cr_dito', label: '70 – Operação de aquisição sem direito a crédito' },
  { value: '71___opera__o_de_aquisi__o_com_isen__o', label: '71 – Operação de aquisição com isenção' },
  { value: '72___opera__o_de_aquisi__o_com_suspens_o', label: '72 – Operação de aquisição com suspensão' },
  { value: '73___opera__o_de_aquisi__o_a_al_quota_zero', label: '73 – Operação de aquisição a alíquota zero' },
  { value: '74___opera__o_de_aquisi__o_sem_incid_ncia_da_contribui__o', label: '74 – Operação de aquisição sem incidência da contribuição' },
  { value: '75___opera__o_de_aquisi__o_por_substitui__o_tribut_ria', label: '75 – Operação de aquisição por substituição tributária' },
  { value: '98___outras_opera__es_de_entrada', label: '98 – Outras operações de entrada' },
  { value: '99___outras_opera__es', label: '99 – Outras operações' },
] as const;
export type cofins_situacao_tributariaValue = typeof cofins_situacao_tributaria[number]['value'];

export const Faixas_atividades_economicas = [
  { value: 'i____com_rcio', label: 'I    Comércio' },
  { value: 'ii____ind_stria', label: 'II    Indústria' },
  { value: 'iii____servi_os_comuns', label: 'III    Serviços comuns' },
  { value: 'iv____servi_os_com_folha_relevante', label: 'IV    Serviços com folha relevante' },
  { value: 'v____servi_os_especializados', label: 'V    Serviços especializados' },
] as const;
export type Faixas_atividades_economicasValue = typeof Faixas_atividades_economicas[number]['value'];

export const icms_situacao_tributaria_nfe = [
] as const;
export type icms_situacao_tributaria_nfeValue = typeof icms_situacao_tributaria_nfe[number]['value'];

export const icms_modalidade_base_calculo = [
  { value: '0___margem_de_valor_agregado____', label: '0 – margem de valor agregado (%)' },
  { value: '1___pauta__valor_', label: '1 – pauta (valor)' },
  { value: '2___pre_o_tabelado_m_ximo__valor_', label: '2 – preço tabelado máximo (valor)' },
  { value: '3___valor_da_opera__o', label: '3 – valor da operação' },
] as const;
export type icms_modalidade_base_calculoValue = typeof icms_modalidade_base_calculo[number]['value'];
