#!/usr/bin/env python3
"""
gen_routes.py — Gera a árvore app/ do Next.js a partir do slice de pages.

Lê:
    slices/01_pages.json

Escreve em <out>/src/app/:
    (public)/login/page.tsx
    (public)/cadastro/page.tsx
    (public)/reset_pw/page.tsx
    (auth)/layout.tsx                 — guard de sessão + current_company
    (auth)/page.tsx                   — index (dashboard)
    (auth)/clientes/page.tsx
    (auth)/notas_fiscais/page.tsx
    (auth)/notas_fiscais/[id]/page.tsx
    (auth)/notas_fiscais/emissao/page.tsx
    (auth)/impostos/page.tsx
    (auth)/impostos/novo/page.tsx
    (auth)/configuracoes/page.tsx
    not-found.tsx                     — 404

Uso:
    python3 gen_routes.py ../slices ../../balu-next
"""
from __future__ import annotations
import json, sys
from pathlib import Path

# Heurísticas portáveis. Override por flag CLI quando o app tiver convenções
# diferentes (--public, --skip, --rename).
DEFAULT_PUBLIC = {"login", "signup", "cadastro", "register", "signin",
                  "reset_pw", "reset_password", "forgot", "forgot_password"}
DEFAULT_SKIP   = {"404", "not_found", "error"}

# Convenções automáticas: sufixos comuns no Bubble → segmento Next idiomático.
SUFFIX_MAP = [
    ("_detalhes", "/[id]"),
    ("_detail",   "/[id]"),
    ("_details",  "/[id]"),
    ("_emissao",  "/emissao"),
    ("_new",      "/novo"),
    ("_create",   "/novo"),
    ("_edit",     "/[id]/editar"),
]

def derive_segment(name: str) -> str:
    """index → '', x_detalhes → x/[id], x_emissao → x/emissao, etc."""
    if name == "index": return ""
    for suf, repl in SUFFIX_MAP:
        if name.endswith(suf):
            return name[:-len(suf)] + repl
    return name

STUB_TEMPLATE = '''// @generated by bubble-to-prd/skills/gen_routes.py — stub.
// Para implementar, use a skill `bubble-behavior` ou edite à mão e troque o header
// `@generated` por `@custom` para evitar sobrescrita no próximo run.
export default function {component_name}Page() {{
  return (
    <main className="p-6">
      <h1 className="text-2xl font-semibold">{title}</h1>
      <p className="text-sm text-zinc-500 mt-2">Stub — implementar behavior aqui.</p>
    </main>
  );
}}
'''

AUTH_LAYOUT = '''import { redirect } from 'next/navigation';
import { createServerClient } from '@/lib/supabase/server';

export default async function AuthLayout({ children }: { children: React.ReactNode }) {
  const supabase = await createServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect('/login');

  const { data: profile } = await supabase
    .from('profiles')
    .select('current_company')
    .eq('id', user.id)
    .single();

  // TODO: se !profile?.current_company, abrir popup de criação de empresa
  return (
    <div className="min-h-screen flex">
      {/* TODO: Menu lateral (reusable §6.1) */}
      <aside className="w-60 border-r border-zinc-200 p-4">menu</aside>
      <div className="flex-1">{children}</div>
    </div>
  );
}
'''

PUBLIC_LAYOUT = '''export default function PublicLayout({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen grid place-items-center bg-zinc-50">{children}</div>;
}
'''

ROOT_LAYOUT = '''import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Balu — Gestão Fiscal',
  description: 'Plataforma SaaS de gestão fiscal e contábil',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className="bg-white text-zinc-900 antialiased">{children}</body>
    </html>
  );
}
'''

NOT_FOUND = '''export default function NotFound() {
  return (
    <main className="min-h-screen grid place-items-center">
      <div className="text-center">
        <h1 className="text-6xl font-semibold text-teal-600">404</h1>
        <p className="mt-2 text-zinc-500">Página não encontrada</p>
      </div>
    </main>
  );
}
'''


def to_component(segment: str) -> str:
    if not segment: return "Index"
    parts = [p for p in segment.replace("[","").replace("]","").split("/") if p]
    return "".join(s[:1].upper() + s[1:] for s in parts) or "Page"


def write(p: Path, content: str):
    p.parent.mkdir(parents=True, exist_ok=True)
    if p.exists():
        existing = p.read_text()
        if "@custom" in existing[:300]:
            print(f"  ⏭  {p} (marcado @custom — não sobrescrito)")
            return
    p.write_text(content)
    print(f"  ✓ {p}")


def main():
    if len(sys.argv) < 3:
        print("Uso: gen_routes.py <slices_dir> <out_dir>"); sys.exit(1)
    slices = Path(sys.argv[1])
    out = Path(sys.argv[2])
    app_dir = out / "src" / "app"
    app_dir.mkdir(parents=True, exist_ok=True)

    pages_data = json.loads((slices / "01_pages.json").read_text())
    pages = pages_data.get("pages", {})

    # Layouts
    write(app_dir / "layout.tsx", ROOT_LAYOUT)
    write(app_dir / "not-found.tsx", NOT_FOUND)
    write(app_dir / "(public)" / "layout.tsx", PUBLIC_LAYOUT)
    write(app_dir / "(auth)" / "layout.tsx", AUTH_LAYOUT)
    write(app_dir / "globals.css", "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n")

    # Pages
    for pid, pg in pages.items():
        name = pg.get("name")
        if not name or name in DEFAULT_SKIP: continue
        # ignora pages utilitárias/test (heurística: começam com test_/teste_/_)
        if name.startswith(("test_", "teste_", "_")): continue
        segment = derive_segment(name)
        group = "(public)" if name in DEFAULT_PUBLIC else "(auth)"
        if segment == "":
            target = app_dir / group / "page.tsx"
        else:
            target = app_dir / group / segment / "page.tsx"
        component = to_component(segment) or to_component(name)
        title = name.replace("_", " ").title()
        write(target, STUB_TEMPLATE.format(component_name=component, title=title))


if __name__ == "__main__":
    main()
