-- @generated by bubble-to-prd/skills/gen_schema.py — edits são sobrescritos no próximo run.
-- Para customizar, adicione migrations 0002+ ao lado.
-- Schema inicial Balu (Bubble → Supabase Postgres)

create extension if not exists "pgcrypto";

-- ─────────────────────────────────────────────────────
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  current_company uuid,
  empresa_fiscal_id uuid,
  logo text,
  background_color text,
  user_role text not null default 'empresa' check (user_role in ('empresa','contador')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ─────────────────────────────────────────────────────
create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  nome text,
  razao_social text,
  cnpj text not null,
  inscricao_estadual text,
  inscricao_municipal text,
  codigo_municipio text,
  logradouro text,
  numero text,
  complemento text,
  bairro text,
  municipio text,
  uf text,
  cep text,
  telefone text,
  email text,
  status text default 'active' check (status in ('active','inactive')),
  deleted_at timestamptz,
  bubble_id text unique,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ─────────────────────────────────────────────────────
create table if not exists public.clientes (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references auth.users(id) on delete cascade not null,
  company_id uuid references companies(id) on delete cascade not null,
  person_type text check (person_type in ('PF','PJ')),
  razao_social text,
  document text not null,
  inscricao_estadual text,
  indicador_inscricao_estadual smallint check (indicador_inscricao_estadual in (1,2,9)),
  inscricao_municipal text,
  codigo_municipio text,
  email text,
  telefone text,
  logradouro text,
  numero text,
  complemento text,
  bairro text,
  municipio text,
  uf text,
  cep text,
  pais text default 'Brasil',
  status text default 'active' check (status in ('active','inactive')),
  deleted_at timestamptz,
  bubble_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ─────────────────────────────────────────────────────
create table if not exists public.empresas_fiscais (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid references companies(id) on delete cascade not null,
  unique_id_bubble text unique,
  municipio_id uuid,
  cnpj text,
  regime_tributario text,
  Code_regime_tributario smallint check (Code_regime_tributario between 1 and 4),
  cnae_principal text,
  anexo_simples text,
  usa_fator_r boolean default false,
  inscricao_municipal text,
  serie_rps text,
  numero_rps_inicial integer,
  login_responsavel text,
  senha_responsavel text,
  token_portal text,
  requer_liberacao_rps boolean default false,
  requer_liberacao_webservice boolean default false,
  requer_aidf boolean default false,
  requer_cadastro_homologacao boolean default false,
  emitir_nota_homol_antes_producao boolean default false,
  credenciais_por_ambiente boolean default false,
  requer_token_portal boolean default false,
  im_zeros_esquerda boolean default false,
  requer_cadastro_tomador boolean default false,
  valor_iss_obrigatorio boolean default false,
  cancelamento_so_portal boolean default false,
  serie_rps_so_numeros boolean default false,
  nfse_autenticacao_tipo text,
  nfse_usuario_login text,
  nfse_senha_login text,
  nfse_token_api text,
  nfse_frase_secreta text,
  nfse_chave_api text,
  nfse_url_portal_producao text,
  nfse_url_portal_homologacao text,
  empresa_fiscal_ativada boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ─────────────────────────────────────────────────────
create table if not exists public.notas_fiscais (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references companies(id) on delete cascade not null,
  cliente_id uuid references clientes(id) on delete set null,
  tipo_nf text check (tipo_nf in ('nfe','nfce','nfse')) not null,
  ref text unique,
  numero_nf text,
  serie text,
  chave_acesso text,
  protocolo_autorizacao text,
  data_emissao timestamptz,
  valor_total numeric(14,2),
  status text default 'pendente' check (status in ('pendente','ativa','cancelada')),
  xml_url text,
  pdf_url text,
  qrcode text,
  focus_response jsonb,
  cancelled_at timestamptz,
  cancellation_reason text,
  bubble_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ─────────────────────────────────────────────────────
create table if not exists public.apuracoes_fiscais (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid references companies(id) on delete cascade not null,
  competencia char(6) not null,
  receita_interno numeric(14,2) default 0,
  receita_externo numeric(14,2) default 0,
  irpj numeric(14,2) default 0,
  csll numeric(14,2) default 0,
  cofins numeric(14,2) default 0,
  pis numeric(14,2) default 0,
  inss_cpp numeric(14,2) default 0,
  icms numeric(14,2) default 0,
  iss numeric(14,2) default 0,
  total_tributos numeric(14,2) default 0,
  deducoes numeric(14,2) default 0,
  total numeric(14,2) default 0,
  rbt12 numeric(14,2),
  aliquota_efetiva numeric(7,4),
  anexo text,
  created_at timestamptz default now()
);

-- ─────────────────────────────────────────────────────
create table if not exists public.aux_produtos (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references companies(id) on delete cascade not null,
  codigo text,
  descricao text not null,
  ncm text,
  cfop text,
  tipo_nf text check (tipo_nf in ('nfe','nfce','nfse')),
  unidade_comercial text default 'UN',
  quantidade_comercial numeric(14,4) default 1,
  valor_unitario_comercial numeric(14,4) default 0,
  finalizado boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ─────────────────────────────────────────────────────
create table if not exists public.declaracoes_fiscais (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid references companies(id) on delete cascade not null,
  competencia char(6) not null,
  tipo_declaracao text,
  data_envio timestamptz,
  status text default 'pronta para enviar' check (status in ('pronta para enviar','enviando','enviada','erro')),
  protocolo text,
  xml_url text,
  pdf_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ─────────────────────────────────────────────────────
create table if not exists public.guias_fiscais (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid references companies(id) on delete cascade not null,
  competencia char(6) not null,
  tipo_guia text default 'DAS',
  data_vencimento date,
  valor_total numeric(14,2),
  status text default 'gerando' check (status in ('gerando','gerada','paga','vencida','erro')),
  pdf_url text,
  linha_digitavel text,
  data_pagamento timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ─────────────────────────────────────────────────────
create table if not exists public.arquivos_auxiliares (
  id uuid primary key default gen_random_uuid(),
  unique_id_empresa uuid references companies(id) on delete cascade,
  unique_id_bubble text,
  supabase_file_path text,
  cert_password text,
  created_at timestamptz default now()
);

-- ─────────────────────────────────────────────────────
create table if not exists public.municipios_nfse (
  id uuid primary key default gen_random_uuid(),
  codigo_ibge text unique not null,
  nome_municipio text,
  uf char(2),
  padrao_nfse text,
  provedor_nfse text,
  url_producao text,
  url_homologacao text,
  requer_certificado boolean default false,
  requer_login boolean default false,
  requer_liberacao_rps boolean default false,
  requer_liberacao_webservice boolean default false,
  requer_aidf boolean default false,
  requer_cadastro_homologacao boolean default false,
  requer_cadastro_tomador boolean default false,
  requer_token_portal boolean default false,
  im_zeros_esquerda boolean default false,
  cancelamento_so_portal boolean default false,
  serie_rps_so_numeros boolean default false,
  valor_iss_obrigatorio boolean default false,
  campo_serie_rps text
);

-- ─────────────────────────────────────────────────────
create table if not exists public.honorarios (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid references clientes(id) on delete cascade not null,
  company_id uuid references companies(id) on delete cascade not null,
  mes_referencia char(6) not null,
  valor numeric(14,2) not null,
  data_vencimento date,
  data_pagamento timestamptz,
  status text default 'pendente' check (status in ('pendente','pago','vencido')),
  observacao text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ─────────────────────────────────────────────────────
create table if not exists public.abertura_empresas (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  company_id uuid references companies(id) on delete set null,
  titular_rg text,
  titular_cpf text,
  titular_nome_mae text,
  titular_naturalidade text,
  titular_estado_civil text,
  titular_endereco jsonb,
  opcao_razao_social_1 text,
  opcao_razao_social_2 text,
  opcao_razao_social_3 text,
  nome_fantasia text,
  tipo_societario text,
  capital_social numeric(14,2),
  objeto_social text,
  cnae text,
  regime_pretendido text,
  endereco_sede jsonb,
  anexos jsonb,
  processo_etapa text default 'recebido',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ─── Constraints adicionais ─────────────────────────
alter table public.profiles add constraint profiles_current_company_fk foreign key (current_company) references public.companies(id) on delete set null;
alter table public.profiles add constraint profiles_empresa_fiscal_fk foreign key (empresa_fiscal_id) references public.empresas_fiscais(id) on delete set null;
-- dedup: 1 cliente por documento por dono (PRD §15.2)
create unique index if not exists clientes_owner_doc_uniq on public.clientes (owner_user_id, document) where deleted_at is null;
-- 1 empresa por CNPJ por dono
create unique index if not exists companies_owner_cnpj_uniq on public.companies (user_id, cnpj) where deleted_at is null;

-- ─── updated_at triggers ────────────────────────────
create or replace function public.tg_set_updated_at() returns trigger
language plpgsql as $$ begin new.updated_at := now(); return new; end; $$;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.tg_set_updated_at();
create trigger companies_set_updated_at before update on public.companies for each row execute function public.tg_set_updated_at();
create trigger clientes_set_updated_at before update on public.clientes for each row execute function public.tg_set_updated_at();
create trigger empresas_fiscais_set_updated_at before update on public.empresas_fiscais for each row execute function public.tg_set_updated_at();
create trigger notas_fiscais_set_updated_at before update on public.notas_fiscais for each row execute function public.tg_set_updated_at();
create trigger aux_produtos_set_updated_at before update on public.aux_produtos for each row execute function public.tg_set_updated_at();
create trigger declaracoes_fiscais_set_updated_at before update on public.declaracoes_fiscais for each row execute function public.tg_set_updated_at();
create trigger guias_fiscais_set_updated_at before update on public.guias_fiscais for each row execute function public.tg_set_updated_at();
create trigger honorarios_set_updated_at before update on public.honorarios for each row execute function public.tg_set_updated_at();
create trigger abertura_empresas_set_updated_at before update on public.abertura_empresas for each row execute function public.tg_set_updated_at();

-- ─── RLS ─────────────────────────────────────────────
alter table public.profiles enable row level security;
alter table public.companies enable row level security;
alter table public.clientes enable row level security;
alter table public.empresas_fiscais enable row level security;
alter table public.notas_fiscais enable row level security;
alter table public.apuracoes_fiscais enable row level security;
alter table public.aux_produtos enable row level security;
alter table public.declaracoes_fiscais enable row level security;
alter table public.guias_fiscais enable row level security;
alter table public.arquivos_auxiliares enable row level security;
alter table public.municipios_nfse enable row level security;
alter table public.honorarios enable row level security;
alter table public.abertura_empresas enable row level security;

-- profiles: user só lê/edita o próprio
create policy profiles_self on public.profiles for all to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- companies: owner
create policy companies_owner on public.companies for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- helper: empresas do usuário
create or replace function public.user_company_ids() returns setof uuid
language sql stable as $$
  select id from public.companies where user_id = auth.uid();
$$;

create policy clientes_company_scope on public.clientes for all to authenticated using (company_id in (select public.user_company_ids())) with check (company_id in (select public.user_company_ids()));
create policy empresas_fiscais_company_scope on public.empresas_fiscais for all to authenticated using (empresa_id in (select public.user_company_ids())) with check (empresa_id in (select public.user_company_ids()));
create policy notas_fiscais_company_scope on public.notas_fiscais for all to authenticated using (company_id in (select public.user_company_ids())) with check (company_id in (select public.user_company_ids()));
create policy apuracoes_fiscais_company_scope on public.apuracoes_fiscais for all to authenticated using (empresa_id in (select public.user_company_ids())) with check (empresa_id in (select public.user_company_ids()));
create policy declaracoes_fiscais_company_scope on public.declaracoes_fiscais for all to authenticated using (empresa_id in (select public.user_company_ids())) with check (empresa_id in (select public.user_company_ids()));
create policy guias_fiscais_company_scope on public.guias_fiscais for all to authenticated using (empresa_id in (select public.user_company_ids())) with check (empresa_id in (select public.user_company_ids()));
create policy honorarios_company_scope on public.honorarios for all to authenticated using (company_id in (select public.user_company_ids())) with check (company_id in (select public.user_company_ids()));
create policy arquivos_auxiliares_company_scope on public.arquivos_auxiliares for all to authenticated using (unique_id_empresa in (select public.user_company_ids())) with check (unique_id_empresa in (select public.user_company_ids()));
create policy aux_produtos_company_scope on public.aux_produtos for all to authenticated using (company_id in (select public.user_company_ids())) with check (company_id in (select public.user_company_ids()));

-- PRD §3.3: cert_password NUNCA é exposto ao front.
-- Revoga SELECT da coluna; backend usa service_role pra ler.
revoke select (cert_password) on public.arquivos_auxiliares from authenticated;
revoke select (cert_password) on public.arquivos_auxiliares from anon;

-- municipios_nfse: leitura pública para autenticados
create policy municipios_read on public.municipios_nfse for select to authenticated using (true);

-- abertura_empresas: dono
create policy abertura_owner on public.abertura_empresas for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- RPC: vincula empresa ao perfil + define como current
create or replace function public.add_company_to_profile(p_user_id uuid, p_company_id uuid) returns void
language plpgsql security definer as $$
begin
  update public.profiles set current_company = p_company_id where id = p_user_id;
end; $$;

-- Auto-cria profile quando user é criado no auth
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer as $$
begin
  insert into public.profiles (id) values (new.id) on conflict do nothing;
  return new;
end; $$;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();
