// Auto-gerado — catálogo de endpoints lidos do .bubble (80 chamadas).
// Use só pra referência; cada cliente real está em ./focus-nfe, ./serpro, ./n8n.
// Nota: editado à mão (2026-05-29) p/ remover a ref defasada a
// arquivos_auxiliares.unique_id_bubble (coluna dropada na migration 0011). Um
// regen via `npm run gen:clients` reintroduziria a linha — não rodar contra o .bubble legado.
export const ENDPOINTS = [
  { name: "Supabase signin", method: "post", url: "https://llykzqnugdpojwnlontj.supabase.co/auth/v1/signup" },
  { name: "Login Supabase", method: "post", url: "https://llykzqnugdpojwnlontj.supabase.co/auth/v1/token?grant_type=password" },
  { name: "Refreshtoken", method: "post", url: "https://llykzqnugdpojwnlontj.supabase.co/auth/v1/token?grant_type=refresh_token" },
  { name: "Create_client", method: "post", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/clientes" },
  { name: "Create_update", method: "patch", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/clientes?id=eq.[CLIENTE_ID]" },
  { name: "Soft_delete", method: "patch", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/clientes?id=eq.[CLIENTE_ID]" },
  { name: "Buscar_clients", method: "get", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/clientes?company_id=eq.[COMPANY_ID]" },
  { name: "get_Company", method: "get", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/companies?id=eq.[CURRENT_COMPANY_ID]&select=*" },
  { name: "Get Companys", method: "get", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/companies?user_id=eq.[USER_ID]&select=*" },
  { name: "Change Company", method: "patch", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/profiles?id=eq.[USER_ID]" },
  { name: "Create_Company", method: "post", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/companies" },
  { name: "Add_company_profile", method: "post", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/rpc/add_company_to_profile" },
  { name: "Edit_company", method: "patch", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/companies?id=eq.[COMPANY_ID]" },
  { name: "Recover_password", method: "post", url: "https://llykzqnugdpojwnlontj.supabase.co/auth/v1/recover" },
  { name: "Reset_password", method: "put", url: "https://llykzqnugdpojwnlontj.supabase.co/auth/v1/user" },
  { name: "get_profiles", method: "get", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/profiles?id=eq.[USER_ID]&select=*" },
  { name: "Focus Nfe - Get empresa", method: "get", url: "https://api.focusnfe.com.br/v2/cnpjs/[cnpj_numero]" },
  { name: "Create nfse", method: "post", url: "https://homologacao.focusnfe.com.br/v2/nfsen?ref=teste_c_nfse_0" },
  { name: "Create NFE", method: "post", url: "https://homologacao.focusnfe.com.br/v2/nfe?ref=[referencia]" },
  { name: "Create NFCE", method: "post", url: "https://homologacao.focusnfe.com.br/v2/nfce?ref=[ref]" },
  { name: "Get-Nfs", method: "get", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/notas_fiscais?company_id=eq.[company_id]" },
  { name: "Cancel NF", method: "patch", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/notas_fiscais?id=eq.[NOTA_FISCAL_ID]" },
  { name: "Buscar empresa fiscal", method: "get", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/empresas_fiscais?empresa_id=eq.[company_id]" },
  { name: "Guias fiscais", method: "get", url: "https://envsirumquqpmkcayncr.supabase.co/rest/v1/guias_fiscais?empresa_id=eq.[company_id]" },
  { name: "Declara\u00e7\u00f5es fiscais ", method: "get", url: "https://envsirumquqpmkcayncr.supabase.co/rest/v1/declaracoes_fiscais?empresa_id=eq.[company_id]" },
  { name: "apuracao atual", method: "get", url: "https://envsirumquqpmkcayncr.supabase.co/rest/v1/apuracoes_fiscais?empresa_id=eq.[empresa_id]&competencia=eq.[competencia]" },
  { name: "declaracao_atual", method: "get", url: "https://envsirumquqpmkcayncr.supabase.co/rest/v1/declaracoes_fiscais?empresa_id=eq.[empresa_id]&competencia=eq.[competencia]" },
  { name: "guia atual", method: "get", url: "https://envsirumquqpmkcayncr.supabase.co/rest/v1/guias_fiscais?empresa_id=eq.[empresa_id]&competencia=eq.[competencia]" },
  { name: "Consolidacao_receitas", method: "post", url: "https://webhooks.envia.click/webhook/consolidar_receitas_fiscais" },
  { name: "rbt12", method: "post", url: "https://webhooks.envia.click/webhook/calcular_rbt12" },
  { name: "calcular_apuracao_pgdasd", method: "post", url: "https://webhooks.envia.click/webhook/consulta_das_mei" },
  { name: "Criar empresa fiscal", method: "post", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/empresas_fiscais" },
  { name: "Editar empresa fiscal", method: "patch", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/empresas_fiscais?id=eq.[id]" },
  { name: "Adicionar tabela_auxiliar", method: "post", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/arquivos_auxiliares" },
  { name: "Adicionar_bucket", method: "post", url: "https://llykzqnugdpojwnlontj.supabase.co/storage/v1/object/company-certificates/[filename]" },
  { name: "N8N - Mandar credenciais e certificado", method: "post", url: "https://webhooks.envia.click/webhook/post-autenticacao" },
  { name: "Upload_certificado_para N8N", method: "post", url: "https://webhooks.envia.click/webhook/upload-certificado" },
  { name: "Entrada", method: "post", url: "https://gateway.apiserpro.serpro.gov.br/integra-contador/v1/Declarar" },
  { name: "Sa\u00edda", method: "post", url: "https://gateway.apiserpro.serpro.gov.br/integra-contador/v1/Declarar" },
  { name: "Consultar Atividades", method: "post", url: "https://gateway.apiserpro.serpro.gov.br/integra-contador/v1/Declarar" },
  { name: "Consultar guias DAS", method: "post", url: "https://gateway.apiserpro.serpro.gov.br/integra-contador/v1/Declarar" },
  { name: "Empresa fiscal adicionar", method: "post", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/empresas_fiscais" },
  { name: "Empresa fiscal editar_novo", method: "patch", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/empresas_fiscais?unique_id_bubble=eq.[unique_id_bubble]" },
  { name: "Buscar_empresa_fiscal", method: "get", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/empresas_fiscais?unique_id_bubble=eq.[unique_id_bubble]&select=*" },
  { name: "Buscar_solicitacoes_empresas", method: "get", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/abertura_empresas" },
  { name: "Abrir_empresa", method: "post", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/abertura_empresas" },
  { name: "get municipios ", method: "get", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/municipios_nfse?" },
  { name: "Buscar_honorarios", method: "get", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/honorarios" },
  { name: "Criar honorario", method: "post", url: "https://llykzqnugdpojwnlontj.supabase.co/rest/v1/honorarios" },
  { name: "Transmitir declara\u00e7\u00e3o", method: "post", url: "https://gateway.apiserpro.serpro.gov.br/integra-contador-trial/v1/Declarar" },
  { name: "Emitir DAS Padr\u00e3o", method: "post", url: "https://gateway.apiserpro.serpro.gov.br/integra-contador-trial/v1/Emitir" },
  { name: "Emitir DAS Cobran\u00e7a", method: "post", url: "https://gateway.apiserpro.serpro.gov.br/integra-contador-trial/v1/Emitir" },
  { name: " Emitir DAS Avulso", method: "post", url: "https://gateway.apiserpro.serpro.gov.br/integra-contador-trial/v1/Emitir" },
  { name: "Consultar Declara\u00e7\u00f5es do Ano/PA", method: "post", url: "https://gateway.apiserpro.serpro.gov.br/integra-contador-trial/v1/Consultar" },
  { name: "Buscar \u00daltima Declara\u00e7\u00e3o do M\u00eas (guia atual)", method: "post", url: "https://gateway.apiserpro.serpro.gov.br/integra-contador-trial/v1/Consultar" },
  { name: "Consultar Extrato do DAS", method: "post", url: "https://gateway.apiserpro.serpro.gov.br/integra-contador-trial/v1/Consultar" },
  { name: "bTIGR", method: "?", url: "" },
  { name: "bTIGd0", method: "?", url: "" },
  { name: "bTIHM0", method: "?", url: "" },
  { name: "bTJyF", method: "?", url: "" },
  { name: "bTKMI", method: "?", url: "" },
  { name: "bTMkY", method: "?", url: "" },
  { name: "bTKzW", method: "?", url: "" },
  { name: "bTMHb", method: "?", url: "" },
  { name: "bTMHn", method: "?", url: "" },
  { name: "bTMHo", method: "?", url: "" },
  { name: "bTMMS", method: "?", url: "" },
  { name: "bTMNK", method: "?", url: "" },
  { name: "bTMZz", method: "?", url: "" },
  { name: "bTMaW", method: "?", url: "" },
  { name: "bTMbO", method: "?", url: "" },
  { name: "bTMaR", method: "?", url: "" },
  { name: "bTMcQ", method: "?", url: "" },
  { name: "bTNDK", method: "?", url: "" },
  { name: "bTNHu", method: "?", url: "" },
  { name: "bTNEo0", method: "?", url: "" },
  { name: "bTNrM", method: "?", url: "" },
  { name: "bTNrd", method: "?", url: "" },
  { name: "bTNiS", method: "?", url: "" },
  { name: "bTNZp0", method: "?", url: "" },
] as const;