-- @custom — Seed de CNAEs sujeitos a Fator R (Anexo III↔V conforme folha/RBT12).
-- Os mais usados em Serviços Médicos/Saúde, TI, Engenharia/Arquitetura e Representação Comercial.
-- anexo_base = NULL (a decisão III/V depende do cálculo de Fator R) | fator_r = true.
-- Códigos validados contra o catálogo oficial (Focus /v2/codigos_cnae); fabricados/inexistentes
-- foram descartados. Aditiva e idempotente.

INSERT INTO public.cnae_anexo (codigo, anexo_base, fator_r, anexo_iv, descricao) VALUES
  ('3250706', NULL, true, false, 'Serviços de prótese dentária'),
  ('3250709', NULL, true, false, 'Serviço de laboratório óptico'),
  ('4512901', NULL, true, false, 'Representantes comerciais e agentes do comércio de veículos automotores'),
  ('4541201', NULL, true, false, 'Comércio por atacado de motocicletas e motonetas'),
  ('4611700', NULL, true, false, 'Representantes comerciais e agentes do comércio de matérias-primas agrícolas e animais vivos'),
  ('4612500', NULL, true, false, 'Representantes comerciais e agentes do comércio de combustíveis, minerais, produtos siderúrgicos e químicos'),
  ('4613300', NULL, true, false, 'Representantes comerciais e agentes do comércio de madeira, material de construção e ferragens'),
  ('4614100', NULL, true, false, 'Representantes comerciais e agentes do comércio de máquinas, equipamentos, embarcações e aeronaves'),
  ('4615000', NULL, true, false, 'Representantes comerciais e agentes do comércio de eletrodomésticos, móveis e artigos de uso doméstico'),
  ('4616800', NULL, true, false, 'Representantes comerciais e agentes do comércio de têxteis, vestuário, calçados e artigos de viagem'),
  ('4617600', NULL, true, false, 'Representantes comerciais e agentes do comércio de produtos alimentícios, bebidas e fumo'),
  ('4618401', NULL, true, false, 'Representantes comerciais e agentes do comércio de medicamentos, cosméticos e produtos de perfumaria'),
  ('4618402', NULL, true, false, 'Representantes comerciais e agentes do comércio de instrumentos e materiais odonto-médico-hospitalares'),
  ('4618403', NULL, true, false, 'Representantes comerciais e agentes do comércio de jornais, revistas e outras publicações'),
  ('4618499', NULL, true, false, 'Outros representantes comerciais e agentes do comércio especializado em produtos não especificados anteriormente'),
  ('4619200', NULL, true, false, 'Representantes comerciais e agentes do comércio de mercadorias em geral não especializado'),
  ('6201501', NULL, true, false, 'Desenvolvimento de programas de computador sob encomenda'),
  ('6202300', NULL, true, false, 'Desenvolvimento e licenciamento de programas de computador customizáveis'),
  ('6203100', NULL, true, false, 'Desenvolvimento e licenciamento de programas de computador não customizáveis'),
  ('6204000', NULL, true, false, 'Consultoria em tecnologia da informação'),
  ('6209100', NULL, true, false, 'Suporte técnico, manutenção e outros serviços em tecnologia da informação'),
  ('6311900', NULL, true, false, 'Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na Internet'),
  ('6319400', NULL, true, false, 'Portais, provedores de conteúdo e outros serviços de informação na Internet'),
  ('6399200', NULL, true, false, 'Outras atividades de prestação de serviços de informação não especificadas anteriormente'),
  ('7020400', NULL, true, false, 'Atividades de consultoria em gestão empresarial, exceto consultoria técnica específica'),
  ('7111100', NULL, true, false, 'Serviços de arquitetura'),
  ('7112000', NULL, true, false, 'Serviços de engenharia'),
  ('7119701', NULL, true, false, 'Serviços de cartografia, topografia e geodésia'),
  ('7119702', NULL, true, false, 'Atividades de estudos geológicos'),
  ('7119703', NULL, true, false, 'Serviços de desenho técnico relacionados à arquitetura e engenharia'),
  ('7119704', NULL, true, false, 'Serviços de perícia técnica relacionados à segurança do trabalho'),
  ('7119799', NULL, true, false, 'Atividades técnicas relacionadas à engenharia e arquitetura não especificadas anteriormente'),
  ('7490101', NULL, true, false, 'Serviços de tradução, interpretação e similares'),
  ('7490102', NULL, true, false, 'Escafandria e mergulho'),
  ('7490104', NULL, true, false, 'Atividades de intermediação e agenciamento de serviços e negócios em geral, exceto imobiliários'),
  ('8630501', NULL, true, false, 'Atividade médica ambulatorial com recursos para realização de procedimentos cirúrgicos'),
  ('8630502', NULL, true, false, 'Atividade médica ambulatorial com recursos para realização de exames complementares'),
  ('8630503', NULL, true, false, 'Atividade médica ambulatorial restrita a consultas'),
  ('8630504', NULL, true, false, 'Atividade odontológica'),
  ('8630506', NULL, true, false, 'Serviços de vacinação e imunização humana'),
  ('8630507', NULL, true, false, 'Atividades de reprodução humana assistida'),
  ('8630599', NULL, true, false, 'Atividades de atenção ambulatorial não especificadas anteriormente'),
  ('8640201', NULL, true, false, 'Laboratórios de anatomia patológica e citológica'),
  ('8640202', NULL, true, false, 'Laboratórios clínicos'),
  ('8640203', NULL, true, false, 'Serviços de diálise e nefrologia'),
  ('8640204', NULL, true, false, 'Serviços de tomografia'),
  ('8640205', NULL, true, false, 'Serviços de diagnóstico por imagem com uso de radiação ionizante, exceto tomografia'),
  ('8640206', NULL, true, false, 'Serviços de ressonância magnética'),
  ('8640207', NULL, true, false, 'Serviços de diagnóstico por imagem sem uso de radiação ionizante, exceto ressonância magnética'),
  ('8640208', NULL, true, false, 'Serviços de diagnóstico por registro gráfico - ECG, EEG e outros exames análogos'),
  ('8640209', NULL, true, false, 'Serviços de diagnóstico por métodos ópticos - endoscopia e outros exames análogos'),
  ('8640299', NULL, true, false, 'Atividades de serviços de complementação diagnóstica e terapêutica não especificadas anteriormente'),
  ('8650001', NULL, true, false, 'Atividades de enfermagem'),
  ('8650002', NULL, true, false, 'Atividades de profissionais da nutrição'),
  ('8650003', NULL, true, false, 'Atividades de psicologia e psicanálise'),
  ('8650004', NULL, true, false, 'Atividades de fisioterapia'),
  ('8650005', NULL, true, false, 'Atividades de terapia ocupacional'),
  ('8650006', NULL, true, false, 'Atividades de fonoaudiologia'),
  ('8650007', NULL, true, false, 'Atividades de terapia de nutrição enteral e parenteral'),
  ('8650099', NULL, true, false, 'Atividades de profissionais da área de saúde não especificadas anteriormente')
ON CONFLICT (codigo) DO NOTHING;
